server:
  port: 9191
spring:
  datasource:
    url: XXXX
    username: postgres
    password: XXXXXX
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    testWhileIdle: true
    test-on-borrow: true
  jpa:
    open-in-view: true
    
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    

      

       