server:
  port: 9191      
  
spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  datasource:
    url: jdbc:postgresql://user-uaa-test.chp81jh9tqob.sa-east-1.rds.amazonaws.com:5432/
    username: postgres
    password: D#ev012word!%$
    driver-class-name: org.postgresql.Driver
    test-on-borrow: true    
  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

management:
  endpoint:
    health:
      show-details: always
      
      
  